version: '3'

services:
  app:
    image: cotizacion-dolar
    deploy:
      replicas: 7
      restart_policy:
        condition: on-failure
    volumes:
      - ./app_volume:/usr/src/app
    ports:
      - 3000:3000
